### ISSUE TITLE
[YAMLDecoder]Throw error instead of crashing when expecting scalar

### ISSUE THREAD

**Issue by MaximeLM** [jpsim/Yams#102]
Thanks for the lib! I noticed that when trying to use YAMLDecoder, if the expected type for a key is a scalar but the YAML contains an array or an object, the code crashes.

* Version: 0.5.0

* Test code:

```
import Yams

struct TestObject: Decodable {
    let test: String
}

do {
    let string = """
    test:
        - a
        - b
    """
    let object = try YAMLDecoder().decode(TestObject.self, from: string, userInfo: [:])
    print("object: \(object)")
} catch {
    print("error: \(error)")
}
```

* Expected result: The decode method should throw an error
* Actual result: The code crashes on Constructor.swift line 240: 

```
assert(node.isScalar)
return node.scalar!.string
```

**Comment by jpsim** [comment]
Could you please check with `master` to see if this was resolved by #94?

**Comment by MaximeLM** [comment]
```
error: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CLI.TestObject.(CodingKeys in _2DF7BF5C06DDF66E41295ECF626C81F4).test], debugDescription: "Expected to decode String but found Node instead.", underlyingError: nil))
```

Fails as expected 👍

**Comment by jpsim** [comment]
Great, thanks for reporting and checking!
