### ISSUE TITLE
Are multiline values supported?

### ISSUE THREAD

**Issue by SimplyDanny** [jpsim/Yams#106]
I wonder whether multiline values like

```
key: |
    value1
    value2
```

are supported by your library. I always get parse errors trying to read such YAML files.

**Comment by jpsim** [comment]
What parse errors are you getting? Yes, multiline strings with the syntax you shared are supported by Yams.

**Comment by jpsim** [comment]
Here's a small sample program demonstrating how this is parsed:

```swift
let yaml = """
  key: |
    value1
    value2
  """
let parsedYAML = try! Yams.load(yaml: yaml)!
print(parsedYAML)
// Prints:
// [AnyHashable("key"): "value1\nvalue2"]
```

**Comment by SimplyDanny** [comment]
Oh, thank you! It turned out that it was just my inability to write YAML files correctly. Sorry for that.
