### ISSUE TITLE
Parse quoted values as strings

### ISSUE THREAD

**Issue by yonaskolb** [jpsim/Yams#116]
Is it possible to configure Yams to parse a quoted value (single or double quotes) as a string, instead of trying to convert to an assumed Swift type?
```yams
version: "10.10" // want it to parse to "10.10" String instead of 10.1 Float
```
I know it's possible to use an explicit type tag as a workaround, but it would be nice to be able to just quote a value which I thought is the standard way of specifying strings in yaml.
```
version: !!str '10.10' // correctly parses as "10.10"
```
This would fix https://github.com/yonaskolb/XcodeGen/issues/268

**Comment by norio-nomura** [comment]
As I confirmed the behavior of PyYAML, it seems to be a bug that Yams guesses the type ignoring quotes.
I will change this behavior.

**Comment by yonaskolb** [comment]
Fantastic, thank you @norio-nomura! 😄
