### ISSUE TITLE
Issues building with Xcode from a SwiftPM package

### ISSUE THREAD

**Issue by kiliankoe** [jpsim/Yams#130]
Hi 👋 

I included this fantastic package as a dependency in a project of mine. On creating the Xcode project through `swift package generate-xcodeproj` I am no longer able to build with Xcode and getting a bunch of unknown symbol errors.

The issue appears to lie with the following snippet in `Parser.swift`, `Emitter.swift` and `YamlError.swift`.

```swift
#if SWIFT_PACKAGE
import CYaml
#endif
```

If I remove the environment check everything seems to work fine in Xcode and via `swift run` on the commandline. 

I'm sure there's a reason for its existence 🙈 Can this be worked around somehow?

Thanks! 😊

**Comment by norio-nomura** [comment]
If you used Xcode 10 beta 3, that is caused by [SR-7965](https://bugs.swift.org/browse/SR-7965).
Using `swift-4.2-DEVELOPMENT-SNAPSHOT-2018-06-19-a` or later from [snapshots](https://swift.org/download/#snapshots) will fix them.

**Comment by kiliankoe** [comment]
Interesting, thanks! I did try this in Xcode 9 as well and ran into the same issue, but knowing myself I probably just forgot to do a clean build 🙈 

Looks like a fix was already merged into spm, so I guess I'll just wait until the next beta 😊
