### ISSUE TITLE
When built with Carthage, version is 0.0.0

### ISSUE THREAD

**Issue by drekka** [jpsim/Yams#131]
I've been trying to use the Stylist framework which has a dependency on Yams. Stylist is expecting version 1.0.0 of Yams, but when the apps tries to start, it returns this message:

dyld: Library not loaded: @rpath/Yams.framework/Yams
  Referenced from: /Users/derekclarkson/Library/Developer/CoreSimulator/Devices/5951E8ED-55B2-4E70-BDE3-0858F47C7C40/data/Containers/Bundle/Application/9FD14F8C-C4D8-4735-AAC0-46D5C61F74A4/Crux.app/Frameworks/Stylist.framework/Stylist
  Reason: Incompatible library version: Stylist requires version 1.0.0 or later, but Yams provides version 0.0.0

I've no idea at this time why Yams is reporting 0.0.0 as a version.

**Comment by jpsim** [comment]
Please let us know if you find out why this is happening.

**Comment by norio-nomura** [comment]
I opened #132 that would fix this issue.
@drekka Could you please try using following entry in Cartfile?
```yaml
github "jpsim/Yams" "nn-dylib-versions"
```

**Comment by drekka** [comment]
Thanks. Looks like that works just fine.
