### ISSUE TITLE
null/~/NULL/Null parsed as strings, not nil

### ISSUE THREAD

**Issue by finestructure** [jpsim/Yams#157]
I'm probably just holding it wrong but when I try to decode yml values with nil values - which I believe are represented as `null | ~ | NULL | Null` in yml - I get the corresponding `String`s back and not nil:

```
    func test_null_yml() throws {
        let s = """
              n1: ~
              n2: null
              n3: NULL
              n4: Null
              n5:
            """
        struct Test: Decodable {
            let n1: String?
            let n2: String?
            let n3: String?
            let n4: String?
            let n5: String?
        }
        let t = try YAMLDecoder().decode(Test.self, from: s)
        XCTAssertNil(t.n1)  // XCTAssertNil failed: "~"
        XCTAssertNil(t.n2)  // XCTAssertNil failed: "null"
        XCTAssertNil(t.n3)  // XCTAssertNil failed: "NULL"
        XCTAssertNil(t.n4)  // XCTAssertNil failed: "Null"
        XCTAssertNil(t.n5)  // XCTAssertNil failed: ""
    }
```

This is with swift-4.2.1 and Yams

```
          "revision": "26ab35f50ea891e8edefcc9d975db2f6b67e1d68",
          "version": "1.0.1"
```

I see references to all these `null` tags in 
https://github.com/jpsim/Yams/blob/c64a5f2c68a9bd13272e3f665c969144a8d67eb4/Tests/YamsTests/ResolverTests.swift#L16 and so I'm wondering: is there something wrong with my test setup above? Or is this perhaps a 🐛?

**Comment by finestructure** [comment]
PS: For reference, this passes:

```
    func test_null_json() throws {
        let d = """
            {
                "n1": null,
            }
            """.data(using: .utf8)!
        struct Test: Decodable {
            let n1: String?
        }
        let t = try JSONDecoder().decode(Test.self, from: d)
        XCTAssertNil(t.n1)
    }
```

**Comment by norio-nomura** [comment]
Thanks for reporting! This is a bug in `YAMLDecoder`.
I opened #158 that fixes this issue.

**Comment by norio-nomura** [comment]
side note:
`YAMLDecoder` does not use `Resolver` and calls `construct(from:)` directly for each type.
In addition, `decodeNil()` uses `Node.null` that calls `NSNull.construct(from:)`.
https://github.com/jpsim/Yams/blob/master/Sources/Yams/Decoder.swift#L223
