### ISSUE TITLE
Yams.dump dumps numerical String values as Number

### ISSUE THREAD

**Issue by jaynetics** [jpsim/Yams#197]
this seems to be similar to https://github.com/jpsim/Yams/issues/174 though i'm not sure it's the same issue.

```swift
let dict = ["1.0": "2."]
print(try! Yams.dump(object: dict))
```

expected output: `'1.0': '2.'`
actual output: `1.0: 2.`

maybe this is an accepted limitation?

if so, i'd love to know if there is a sane way to correctly dump dicts of an unknown structure. i can only think of deep-mapping them to Nodes and setting styles based on the Strings' contents...

**Comment by norio-nomura** [comment]
If `Resolver.default` determines that the content of `String` is other than `.str`, it would be better to apply `Style.singleQuoted` to `Node.Scalar` when creating from that `String`.
