### ISSUE TITLE
Feature Request - Add support for Swift Package Manager

### ISSUE THREAD

**Issue by travismmorgan** [jpsim/Yams#207]
Currently throws error "No such module 'Yams'"

**Comment by jpsim** [comment]
Can you share steps to reproduce this issue? Yams supports the Swift Package Manager and in fact was used at WWDC to demonstrate Swift Package Manager functionality: https://developer.apple.com/videos/play/wwdc2019/408/

**Comment by travismmorgan** [comment]
@jpsim I tried it with a new project and it worked but for some reason I can't get it to build in my existing project. Keep getting "No such Module 'Yams'". I've tried cleaning the build folder and deleting the derived data with no luck. Any idea what might be causing the issue?

**Comment by jpsim** [comment]
> Any idea what might be causing the issue?

It could be a lot of things. Maybe if you shared steps to reproduce this issue I'd be able to offer more suggestions as to what may be causing this.

**Comment by travismmorgan** [comment]
I originally had Yams installed via pods. I removed the pod, added the repo to the package manager with version rules set to 2.0.0 up to next major, cleaned and build. That is when it throws the error. If I remove the swift package and reinstall the pod, it works fine.

**Comment by jpsim** [comment]
I looks like you resolved this on your own.
