### ISSUE TITLE
Invalid Code Signature Identifier during upload to App Store Connect

### ISSUE THREAD

**Issue by stevenwei** [jpsim/Yams#216]
![Screen Shot 2019-10-22 at 5 34 16 PM](https://user-images.githubusercontent.com/248487/67355738-bc9ac280-f4f3-11e9-991f-501332850cf3.png)

Ran into this issue when uploading a Mac app built with Xcode 11 to App Store Connect. After some digging I discovered that because the Yams Product Bundle Identifier was set to "Yams", Xcode was appending a random string to its code signature identifier during code signing, so it would longer match the original bundle identifier and would fail validation during upload.

The problem is solved by changing the Yams Product Bundle Identifier from "Yams" to something containing a period, e.g: "com.jpsim.Yams". I would suggest updating the Yams project file with this change to prevent anyone else from experiencing the same problem.

(Looks like this behavior is new as of Xcode 11, another user reported a similar problem on Stackoverflow: https://stackoverflow.com/a/58293021)

**Comment by jpsim** [comment]
Thanks for the heads up! Could you file a PR making this change yourself? Otherwise I’ll get to it later this week.

**Comment by jpsim** [comment]
Done in https://github.com/jpsim/Yams/pull/217
