### ISSUE TITLE
lost quote when dump a double string

### ISSUE THREAD

**Issue by Whirlwind** [jpsim/Yams#233]
![image](https://user-images.githubusercontent.com/1251192/69313525-c5a2bf00-0c6c-11ea-8704-8027eb5a83ed.png)

The origin string is `VERSION: "1.0"`, so yams will parse the `1.0` to string value. It is right.
But when dump the object to string, it lost the quote: `VERSION: 1.0`, so the yams will make the `1.0` as a double value.

Is it a bug?

**Comment by Whirlwind** [comment]
It fixed by https://github.com/jpsim/Yams/commit/0e210c0ef36de544a78db8298236c301520000b3

Could you release a new version?

**Comment by jpsim** [comment]
Yes, we'll make sure to cut a release in the coming weeks.
