### ISSUE TITLE
project fails to build via xcodebuild when including Yams via SPM

### ISSUE THREAD

**Issue by robinsenior** [jpsim/Yams#236]
I've created an empty project, and using the new Swift Package Manager features in Xcode 11, added Yams as a Package Dependency to a macOS app. Building in Xcode works fine, but building via `xcodebuild` fails with the error: `<unknown>:0: error: module map file '/Users/robinsenior/src/personal/tests/YamsTest/build/GeneratedModuleMaps/macosx/CYaml.modulemap' not found
`

I've tried doing this same thing with other yaml parsing libraries with no problem. I suspect it's due to Yams' `cyaml` usage, but I don't know if it's a limitation of xcodebuild.

**Comment by jpsim** [comment]
Can you try with Yams on master to see if the explicit module map file we added in https://github.com/jpsim/Yams/pull/210 fixes this?

**Comment by robinsenior** [comment]
Confirmed that it works! Thanks! Will target master for the time being.

**Comment by jpsim** [comment]
Alright I’ll close this knowing that it’s resolved on master.
