### ISSUE TITLE
Allow decode from data

### ISSUE THREAD

**Issue by mitchins** [jpsim/Yams#239]
I couldn't find a mention of the word `data` in Readme.md and just wondering if there's a significant reason that decodeFrom is only available with string not data?

**Comment by MPLew-is** [comment]
This looks like it's been fixed by #262 (6e6483a6dde480bba8f80b67ab62c63de38bc74d).

**Comment by jpsim** [comment]
Right, thanks for the ping.

**Comment by druvinskiy** [comment]
Is there a way to decode from Data without using Combine?

**Comment by MPLew-is** [comment]
@druvinskiy you don't need to use Combine to decode from `Data`, that just seems to have happened to be the motivating factor for adding it. See [the relevant lines in YamlDecoder](https://github.com/jpsim/Yams/blob/6e6483a6dde480bba8f80b67ab62c63de38bc74d/Sources/Yams/Decoder.swift#L56-L64).

**Comment by druvinskiy** [comment]
@MPLew-is Thank you for the information. Unfortunately, autocomplete is only giving me the version of the function that accepts a String and not the version that accepts `Data`. Any ideas why this is happening?

**Comment by jpsim** [comment]
Are you using Yams from master? The Data decoding hasn't made it into a tagged release yet. https://github.com/jpsim/Yams/pull/262

**Comment by druvinskiy** [comment]
Oh, I just installed Yams using Cocoapods. Can you please explain how I should install Yams so I have access to the Data decoding?
