### ISSUE TITLE
Xcode error: "Missing required module 'CYaml'"

### ISSUE THREAD

**Issue by mattt** [jpsim/Yams#244]
I added Yams as a dependency to a Swift library following the installation instructions for Swift Package Manager that are [provided in the README](https://github.com/jpsim/Yams#swift-package-manager):

> Add `.package(url: "https://github.com/jpsim/Yams.git", from: "2.0.0")` to your Package.swift file's dependencies.

Everything worked when I ran unit tests for that library. However, when I tried to add my library as a dependency in a separate project, my (generated) Xcode project for the package became unable to compile, generating the error:

> `Xcode error: "Missing required module 'CYaml'"`

I thought this might be related to #236, and tried pointing the original package to `master`, but that didn't change anything. (On a separate note, it would be nice to have the latest changes on master available in a tagged release).

**Comment by mattt** [comment]
I was able to resolve this by explicitly adding Yams as a dependency to the other project:

```swift
        .package(url: "https://github.com/jpsim/Yams.git", .branch("master")),
```

Is this expected for when Yams is used as a transient dependency?

**Comment by jpsim** [comment]
> I thought this might be related to #236, and tried pointing the original package to `master`, but that didn't change anything

Can you try again after cleaning (I think `rm -rf .build` should do it). I'm wondering if this was due to the info plist not being picked up after an incremental build. Just a guess.

Also, could you share what Xcode version you're using? I haven't done much with Yams using Swift 5.2 or Xcode 11.4 yet.

---

> On a separate note, it would be nice to have the latest changes on master available in a tagged release

Absolutely. We've been holding off a bit because there are significant breaking changes, but it's been a while since we've made any further changes.

**Comment by jpsim** [comment]
Also, this seems like it could be an Xcode bug if the package works well using Swift Package Manager from the command line.

**Comment by mattt** [comment]
Thanks for the quick reply, @jpsim! I'm using Xcode version 11.4 (11E146) and Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29).

Both in Xcode and on the command line, I'm still getting this error after `rm -rf`-ing my `.build` and DerivedData directories: 

```
<unknown>:0: error: missing required module 'CYaml'
```

(Something about my `.build` directory module cache was causing a behavior difference with Xcode when I filed the issue initially, but they're now both failing with the same message)

**Comment by jpsim** [comment]
Ah shame that didn't work.

There are number of projects that use Yams in Xcode using its Swift Package Manager integration without issue, perhaps you could compare them with your project to identify what might be different?

* [apple/swift-driver](https://github.com/apple/swift-driver/blob/0aa21788c63d33fe92dfded7b45900d85e2625cc/Package.swift#L26)
* [jpsim/SourceKitten](https://github.com/jpsim/SourceKitten/blob/f7ee209f705350ba388e0da84d33c0d521d51f9c/Package.swift#L13)
* [realm/SwiftLint](https://github.com/realm/SwiftLint/blob/889dc49bb68d28944909dc1bc833deb423746368/Package.swift#L19)

Also, do you get a build error when compiling your library using Yams from the command line using `swift build` or `swift test`? This is seeming more and more like an Xcode bug to me, but I haven't been able to reproduce so it's hard to say definitively.

**Comment by mattt** [comment]
> There are number of projects that use Yams in Xcode using its Swift Package Manager integration without issue when I build them using Xcode 11.4 (11E146), perhaps you could compare them with your project to identify what might be different?

Indeed there are, and I have no problem using Yams as a direct dependency. It seems that the issue arises when I try to add as a dependency a project that has Yams as a dependency (A depends on B, B depends on Yams; Yams is a transient dependency of A). 

> Also, do you get a build error when compiling your library using Yams from the command line using `swift build` or `swift test`? This is seeming more and more like an Xcode bug to me, but I haven't been able to reproduce so it's hard to say definitively.

I get the same error when I run `swift build` and `swift test`, and when I try to build from Xcode.

**Comment by jpsim** [comment]
> Indeed there are, and I have no problem using Yams as a direct dependency. It seems that the issue arises when I add as a dependency a project that has Yams as a dependency (A depends on B, B depends on Yams; Yams is a transient dependency of A).

Thanks for elaborating on this. For what it’s worth, SwiftLintFramework depends on SourceKittenFramework and in turn both directly depend on Yams, and I have no issues with `swift build|test|run` or SwiftPM via Xcode for either project.

Is there a chance you can share a project where I can reproduce this issue to be able to dig further into it?

**Comment by mattt** [comment]
> Is there a chance you can share a project where I can reproduce this issue to be able to dig further into it?

The project using Yams is [TAP](https://github.com/SwiftDocOrg/TAP) and the project using Yams as a transient dependency is [DocTest](https://github.com/SwiftDocOrg/DocTest).

For whatever reason, this started working again. I honestly don't know what changed in the meantime, which is frustrating. My one suspicion is that it had to do with a module cache error and private git repositories. If I can reproduce it, I'll file a radar against Xcode.

Anyway, thank you for taking the time to respond to my bug report, @jpsim, and for your stewardship of this project generally. It's great to have a core piece of infrastructure like this, and I'm very glad to be using it in my projects.

**Comment by jpsim** [comment]
Well that’s not entirely satisfying 🤔. Since you were also seeing the issue with SwiftPM on the command line, you could probably file a bug at https://bugs.swift.org for greater transparency.

In any case, I’m glad it’s working now.

I’ll be cutting a tagged release shortly.

**Comment by swift-ortal** [comment]
I was getting the same error when importing `SwiftLint`, which eventually uses `Yams`. Solution was to add an explicit dependency to my target on SwiftLint. I believe this is related to "Apps with Dependencies Between Frameworks" and how "The app target is responsible for embedding all of the frameworks, including any frameworks that other frameworks depend on." Source: https://developer.apple.com/library/archive/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-PROJ_CONFIG-APPS_WITH_DEPENDENCIES_BETWEEN_FRAMEWORKS

**Comment by kvaDrug** [comment]
I had similar problem in UI test target, adding Yams directly to that target helped.
