### ISSUE TITLE
Special FP names are inconsistent

### ISSUE THREAD

**Issue by compnerd** [jpsim/Yams#258]
On Windows, I am seeing `-.infe+0`, `.infe+0`, and `nane+0` instead of `-.inf`, `.inf`, and `nan`.  I cannot identify where the conversion from the value to the name is occuring.

A second type of incompatibility occurs with the spec test with `NaN` being used instead of `nan`.  AIUI, `NaN` and `nan` are interchangable as per the C standard, and that should be accepted as equivalent unless the string representation is being constructed explicitly in the Swift side of the code.

**Comment by compnerd** [comment]
@jpsim any hints on where to go hunting down these issues?

**Comment by compnerd** [comment]
```
Test Case 'EncoderTests.testValuesInSingleValueContainer' started at 2020-05-14 16:49:53.933
S:\SourceCache\Yams\Tests\YamsTests\EncoderTests.swift:169: error: EncoderTests.testValuesInSingleValueContainer : failed - Failed to decode Float from YAML by error: valueNotFound(Swift.Float, Swift.DecodingError.Context(codingPath: [], debugDescription: "Expected Float value but found Scalar(string: \".infe+0\", tag: , style: Yams.Node.Scalar.Style.plain, mark: Optional(1:1)) instead.", underlyingError: nil))
S:\SourceCache\Yams\Tests\YamsTests\EncoderTests.swift:170: error: EncoderTests.testValuesInSingleValueContainer : failed - Failed to decode Double from YAML by error: valueNotFound(Swift.Double, Swift.DecodingError.Context(codingPath: [], debugDescription: "Expected Double value but found Scalar(string: \".infe+0\", tag: , style: Yams.Node.Scalar.Style.plain, mark: Optional(1:1)) instead.", underlyingError: nil))
Test Case 'EncoderTests.testValuesInSingleValueContainer' failed (0.0 seconds)
...
Test Case 'RepresenterTests.testDouble' started at 2020-05-14 16:49:54.392
S:\SourceCache\Yams\Tests\YamsTests\RepresenterTests.swift:42: error: RepresenterTests.testDouble : XCTAssertEqual failed: ("scalar(Yams.Node.Scalar(string: ".infe+0", tag: tag:yaml.org,2002:float, style: Yams.Node.Scalar.Style.any, mark: nil))") is not equal to ("scalar(Yams.Node.Scalar(string: ".inf", tag: , style: Yams.Node.Scalar.Style.any, mark: nil))") -
S:\SourceCache\Yams\Tests\YamsTests\RepresenterTests.swift:43: error: RepresenterTests.testDouble : XCTAssertEqual failed: ("scalar(Yams.Node.Scalar(string: "-.infe+0", tag: tag:yaml.org,2002:float, style: Yams.Node.Scalar.Style.any, mark: nil))") is not equal to ("scalar(Yams.Node.Scalar(string: "-.inf", tag: , style: Yams.Node.Scalar.Style.any, mark: nil))") -
S:\SourceCache\Yams\Tests\YamsTests\RepresenterTests.swift:44: error: RepresenterTests.testDouble : XCTAssertEqual failed: ("scalar(Yams.Node.Scalar(string: ".nane+0", tag: tag:yaml.org,2002:float, style: Yams.Node.Scalar.Style.any, mark: nil))") is not equal to ("scalar(Yams.Node.Scalar(string: ".nan", tag: , style: Yams.Node.Scalar.Style.any, mark: nil))") -
Test Case 'RepresenterTests.testDouble' failed (0.0 seconds)
Test Case 'RepresenterTests.testFloat' started at 2020-05-14 16:49:54.392
S:\SourceCache\Yams\Tests\YamsTests\RepresenterTests.swift:52: error: RepresenterTests.testFloat : XCTAssertEqual failed: ("scalar(Yams.Node.Scalar(string: ".infe+0", tag: tag:yaml.org,2002:float, style: Yams.Node.Scalar.Style.any, mark: nil))") is not equal to ("scalar(Yams.Node.Scalar(string: ".inf", tag: , style: Yams.Node.Scalar.Style.any, mark: nil))") -
S:\SourceCache\Yams\Tests\YamsTests\RepresenterTests.swift:53: error: RepresenterTests.testFloat : XCTAssertEqual failed: ("scalar(Yams.Node.Scalar(string: "-.infe+0", tag: tag:yaml.org,2002:float, style: Yams.Node.Scalar.Style.any, mark: nil))") is not equal to ("scalar(Yams.Node.Scalar(string: "-.inf", tag: , style: Yams.Node.Scalar.Style.any, mark: nil))") -
S:\SourceCache\Yams\Tests\YamsTests\RepresenterTests.swift:54: error: RepresenterTests.testFloat : XCTAssertEqual failed: ("scalar(Yams.Node.Scalar(string: ".nane+0", tag: tag:yaml.org,2002:float, style: Yams.Node.Scalar.Style.any, mark: nil))") is not equal to ("scalar(Yams.Node.Scalar(string: ".nan", tag: , style: Yams.Node.Scalar.Style.any, mark: nil))") -
Test Case 'RepresenterTests.testFloat' failed (0.0 seconds)
...
Test Case 'SpecTests.testSpecExample2_20_FloatingPoint' started at 2020-05-14 16:49:54.402
S:\SourceCache\Yams\Tests\YamsTests\SpecTests.swift:664: error: SpecTests.testSpecExample2_20_FloatingPoint : XCTAssertEqual failed: ("canonical: 1.23015e+3
exponential: 1.23015e+3
fixed: 1.23015e+3
negative infinity: -.infe+0
not a number: .nane+0
") is not equal to ("canonical: 1.23015e+3
exponential: 1.23015e+3
fixed: 1.23015e+3
negative infinity: -.inf
not a number: .nan
") -
Test Case 'SpecTests.testSpecExample2_20_FloatingPoint' failed (0.0 seconds)
```

**Comment by jpsim** [comment]
I suspect this difference in string representations for floating point values is a discrepancy either the swift standard library itself, or swift-corelibs-foundation.

Can you share more detailed steps of how I could run the test suite on Windows so I can debug?

**Comment by compnerd** [comment]
Sure; the cmake invocation that you shared earlier actually is pretty much it.  I just did:

```
cmake -B S:\BinaryCache\Release\Windows-x86_64\Yams -D BUILD_SHARED_LIBS=YES -D CMAKE_BUILD_TYPE=Release -D Foundation_DIR=S:\BinaryCache\Release\Windows-x86_64\swift-corelibs-foundation\cmake\modules -D dispatch_DIR=S:\BinaryCache\Release\Windows-x86_64\swift-corelibs-libdispatch\cmake\modules -D XCTest_DIR=S:\BinaryCache\Release\Windows-x86_64\swift-corelibs-xctest\cmake\modules -D ArgumentParser_DIR=S:\BinaryCache\Release\Windows-x86_64\swift-argument-parser\cmake\modules -S S:\SourceCache\Yams
```

Note that if you are using the installer from Azure or the releases from GitHub, then it will require passing `CMAKE_Swift_FLAGS` as follows instead of `dispatch_DIR`, `Foundation_DIR`, and `XCTest_DIR`:

```
-D CMAKE_Swift_FLAGS="-sdk %SDKROOT% -I %SDKROOT%/usr/lib/swift -L %SDKROOT%/usr/lib/swift/windows -I %DEVELOPER_LIBRARY_DIR%/XCTest-development/usr/lib/swift/windows/x86_64 -L %DEVELOPER_LIBRARY_DIR%/XCTest-development/usr/lib/swift/windows "
```

This uses a few variables as:
```
set SDKROOT=%SystemDrive%/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk
set DEVELOPER_LIBRARY_DIR=%SystemDrive%/Library/Developer/Platforms/Windows.platform/Developer/Library
```

**Comment by compnerd** [comment]
Would you be able to help point out where those conversions from Foundation or the stdlib occur?  It might help find which of the two are responsible.

**Comment by jpsim** [comment]
I created a Windows VM on Azure and started following the build steps [here](https://github.com/apple/swift/blob/master/docs/WindowsBuild.md) and quickly got discouraged, so I won't be looking further into that.

> Would you be able to help point out where those conversions from Foundation or the stdlib occur? It might help find which of the two are responsible.

I was able to reduce the production of `-.inf` on macOS with the following test:

```swift
func testNumberFormatterWindowsDiscrepancies() {
    let formatter = NumberFormatter()
    formatter.locale = Locale(identifier: "en_US")
    formatter.numberStyle = .scientific
    formatter.usesSignificantDigits = true
    formatter.maximumSignificantDigits = 15
    formatter.positiveInfinitySymbol = ".inf"
    formatter.negativeInfinitySymbol = "-.inf"
    formatter.notANumberSymbol = ".nan"
    formatter.exponentSymbol = "e+"
    XCTAssertEqual(formatter.string(for: -1 * Double.infinity), "-.inf")
}
```

That doesn't depend on anything in Yams and you should be able to run that using just Swift and Foundation on macOS, Linux and Windows. From there you should be able to isolate why Windows is producing `-.infe+0` where macOS and Linux are producing `-.inf`.

**Comment by compnerd** [comment]
Personally, I would recommend that you start from the the prebuilt toolchains from https://github.com/compnerd/swift-build or an Azure nightly build rather than build the toolchain to debug this.  That seems like a rather large process for something further up the build tree.

That said, I'll definitely try this test case.  If it works, do I have permission to use this in the Foundation test suite?

**Comment by jpsim** [comment]
Are there canonical instructions for getting a prebuilt toolchain running on windows anywhere?

> That said, I'll definitely try this test case. If it works, do I have permission to use this in the Foundation test suite?

Yes absolutely.

**Comment by compnerd** [comment]
https://github.com/compnerd/swift-build/blob/master/docs/GettingStartedWindows.md has some instructions; if anything is unclear, please let me know, I'd love to improve them so that it is easier for people to get started.

I actually managed to reduce the amazing test case you provided a bit further.  It is absolutely an issue outside of Yams - the problem is with ICU's conversion of the floating point.  Reduced, extended tests:
https://github.com/apple/swift-corelibs-foundation/pull/2798

This leads down the path to: https://github.com/apple/swift-corelibs-foundation/blob/master/CoreFoundation/Locale.subproj/CFNumberFormatter.c#L489

**Comment by jpsim** [comment]
I’m glad you were able to further reduce! I’ll give the Windows instructions you shared a try later too.

**Comment by compnerd** [comment]
Oh, btw, I looked into this deeper (thank you so much for the original test case).  It turns out its an ICU issue, which should be fixed with a newer ICU.  Im trying to see if I can get a newer ICU built and used, and at that point, we should have all the tests passing on Windows as well!

**Comment by compnerd** [comment]
I'm not sure if you want to keep the issue open or if you would like to close it.  After the original reduction you provided, you had demonstrated the issue was not related to Yams, I don't think that there is anything that you do here unless you want to provide compatibility for older versions.  I think it is safe to close this off, but, I'll wait for a response.

**Comment by jpsim** [comment]
I’m glad to hear an ICU update will resolve this. Closing.
