### ISSUE TITLE
make YAMLDecoder compliant to TopLevelDecoder to be used with Combine.decode

### ISSUE THREAD

**Issue by marcblanchet** [jpsim/Yams#261]
would be cool to chain with Combine .decode(type: ..., decoder: YAMLDecoder()) but YAMLDecoder is not compliant with protocol TopLevelDecoder. XMLCoder does it and it is really useful

**Comment by jpsim** [comment]
Thanks for the suggestion! In the meantime, you should be able to add the conformance in your own code:

```swift
extension YAMLDecoder: TopLevelDecoder {
    public typealias Input = String

    public func decode<T>(_ type: T.Type, from: String) throws -> T where T : Decodable {
        try self.decode(type, from: from, userInfo: [:])
    }
}
```

**Comment by jpsim** [comment]
Started a PR tracking the work left to do here: https://github.com/jpsim/Yams/pull/262

**Comment by marcblanchet** [comment]
suggested code seems halfway. If I do:
extension URLSession {
enum SessionErrorHTTP: Error {
    case statusCode(HTTPURLResponse)
  }
func dataTaskPublisher<T: Decodable>(for request: URLRequest) -> AnyPublisher<T, Error> {
    return self.dataTaskPublisher(for: request)
      .tryMap({ (data, response) -> Data in
        if let response = response as? HTTPURLResponse,
          (200..<300).contains(response.statusCode) == false {
          throw SessionErrorHTTP.statusCode(response)
        }
        return data
      })
      .decode(type: T.self, decoder: JSONDecoder())
      .eraseToAnyPublisher()
  }

I can replace JSONDecoder() above with XMLCoder or CSVDecoder, but not yet YAMLDecoder (even with your suggestion). Some piece is missing.

**Comment by jpsim** [comment]
With my provided code, you need to give the decoder a `String` instead of `Data`.

**Comment by marcblanchet** [comment]
thanks a bunch! will test it!
