### ISSUE TITLE
Is it possible to keep the comments in yaml?

### ISSUE THREAD

**Issue by owenzhao** [jpsim/Yams#276]
I am working on a config wizard of Clash. https://lancellc.gitbook.io/clash/clash-config-file/an-example-configuration-file
I believe it is more desirable to leave the comments along with the config parts. However, if I decode and encode with Yams, the comments are gone. It there any way to keep them?

**Comment by jpsim** [comment]
Yams is built around libyaml, and that's not something it currently supports: https://github.com/yaml/libyaml/issues/42

**Comment by owenzhao** [comment]
> Yams is built around libyaml, and that's not something it currently supports: [yaml/libyaml#42](https://github.com/yaml/libyaml/issues/42)

Thank you for your reply. In this case, I have to just splitting and joining the yamls when encoding.
