### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ileitch** [jpsim/Yams#287]
It'd be great to get a new release cut if possible, so that we may benefit from https://github.com/jpsim/Yams/pull/273

**Comment by jpsim** [comment]
Sure I'll cut a release. Thanks for the nudge!

**Comment by jpsim** [comment]
I just tagged [4.0.1](https://github.com/jpsim/Yams/releases/tag/4.0.1) and published on CocoaPods.

**Comment by ileitch** [comment]
Thank you 🙇
