### ISSUE TITLE
`Yams.Error` should expose details to consumer

### ISSUE THREAD

**Issue by norio-nomura** [jpsim/Yams#3]
Two properties of `Error` are declared as `internal`.
Those should be exposed to consumer for better error handling.
Are there any plans for improving `Error`?

**Comment by jpsim** [comment]
I whipped this project up super quickly, so there's a ton of room for improvement. Exposing more info on `Error` is a good first step. If I ever find the time, I'd like to expose an interface similar to YamlSwift.
