### ISSUE TITLE
SSL certificate issue when attempting to clone yams repo

### ISSUE THREAD

**Issue by liquidoshin** [jpsim/Yams#317]
A program I'm writing implements the yams package. I didn't have this problem before but after stepping away from the project and coming back to it, when I attempt to do a swift build for our project, I get the following error:

fatal: unable to access 'https://github.com/jpsim/Yams/': SSL certificate problem: self signed certificate in certificate chain

This was never an issue before. Not sure if it's due to a change to the yams package or if something changed within my environment. Any idea what's going on here?

**Comment by jpsim** [comment]
Are you using the Swift Package Manager? If so, can you report this (with more information) at bugs.swift.org?

Yams is hosted on GitHub and GitHub manages the SSL certificate used when cloning the repo. I have no control over that.
