### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by yonaskolb** [jpsim/Yams#32]
Hi. Any chance of getting a new tagged version, so that a build can be installed via SwiftPM that supports Swift 3.1 on Linux?

**Comment by jpsim** [comment]
Yeah, I'll take care of this now.

**Comment by jpsim** [comment]
Tag: https://github.com/jpsim/Yams/releases/tag/0.3.0
CocoaPods: https://github.com/CocoaPods/Specs/commit/c66d52b9edf3897d0caa4f228a92cf3d7b9f67cf

**Comment by norio-nomura** [comment]
Thanks! 🙏
