### ISSUE TITLE
Should we remove {loader,dumper}.c?

### ISSUE THREAD

**Issue by jpsim** [jpsim/Yams#62]
Neither of these files are used, but we're still compiling them. Should we just remove them?

**Comment by norio-nomura** [comment]
Since it is necessary to follow upstream changes of libYAML, it may be better to review at that time.

**Comment by jpsim** [comment]
Couldn't we easily add them back if they become useful?

**Comment by norio-nomura** [comment]
Sure. 👍 
I opened PR.
