### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by jpsim** [jpsim/Yams#70]
Let's follow the same format as [SourceKitten](https://github.com/jpsim/SourceKitten/blob/master/CHANGELOG.md), SwiftLint, etc.

**Comment by yonaskolb** [comment]
🎉

**Comment by jpsim** [comment]
This project hasn’t been ready for external use until now, but things are in pretty good shape thanks to Norio.

**Comment by jpsim** [comment]
Done in #76.
